// src/components/AboutSection.tsx
import React, { useEffect, useRef } from 'react';
import { Moon, Star, Sun } from 'lucide-react';

const AboutSection: React.FC = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-fade-in');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => {
      if (sectionRef.current) {
        observer.unobserve(sectionRef.current);
      }
    };
  }, []);

  return (
    <section id="about" className="py-20 relative overflow-hidden">
      <div className="absolute inset-0 opacity-10 z-0">
        <div className="absolute top-20 left-10 text-purple-300">
          <Moon size={60} />
        </div>
        <div className="absolute bottom-20 right-10 text-yellow-300">
          <Sun size={80} />
        </div>
        <div className="absolute top-1/3 right-1/4 text-white">
          <Star size={40} />
        </div>
        <div className="absolute bottom-1/3 left-1/4 text-white">
          <Star size={30} />
        </div>
      </div>

      <div 
        ref={sectionRef}
        className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10 opacity-0 transition-opacity duration-1000"
      >
        <div className="text-center mb-12">
          <h2 className="text-3xl sm:text-4xl font-serif font-bold text-white mb-2">About Me</h2>
          <div className="w-20 h-1 bg-purple-500 mx-auto"></div>
        </div>

        <div className="flex flex-col lg:flex-row items-center gap-12">
          <div className="lg:w-1/2">
            <div className="relative">
              <div className="absolute inset-0 bg-gradient-to-r from-purple-500 to-indigo-600 rounded-full transform translate-x-2 translate-y-2"></div>
              <img
                src="https://images.pexels.com/photos/9996378/pexels-photo-9996378.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"
                alt="Astrologer portrait"
                className="relative z-10 rounded-full w-64 h-64 sm:w-80 sm:h-80 object-cover mx-auto border-4 border-indigo-200"
              />
              <div className="absolute -top-4 -right-4 text-purple-300">
                <Star size={40} className="animate-pulse" />
              </div>
              <div className="absolute -bottom-4 -left-4 text-indigo-300">
                <Moon size={40} className="animate-pulse" />
              </div>
            </div>
          </div>

          <div className="lg:w-1/2 text-center lg:text-left">
            <h3 className="text-2xl font-serif font-semibold text-purple-300 mb-4">
              Alexandra Starlight
            </h3>
            <p className="text-gray-200 mb-6 leading-relaxed">
              With over 15 years of experience in celestial navigation, I've guided hundreds of souls through their cosmic journeys. My connection to the stars began at a young age when I experienced profound visions that connected me to the universal energy.
            </p>
            <p className="text-gray-200 mb-6 leading-relaxed">
              I combine traditional astrological wisdom with modern psychological insights to provide you with readings that are both spiritually enriching and practically applicable to your everyday life.
            </p>
            <h4 className="text-xl font-serif font-medium text-white mb-3">My Mission</h4>
            <p className="text-gray-200 leading-relaxed">
              To illuminate your path through the cosmos, helping you understand your unique celestial blueprint and harness the energy of the stars to create the life you desire and deserve.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AboutSection;

// src/components/AboutSection.vue
<script setup>
import { Heart, Award, Users } from 'lucide-vue-next'
</script>

<template>
  <section id="about" class="section">
    <div class="container">
      <div class="about-content">
        <div class="about-image fade-in">
          <div class="image-container">
            <img 
              src="https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=400&h=400&fit=crop" 
              alt="Professional Astrologer"
              class="astrologer-photo"
            />
            <div class="image-glow"></div>
          </div>
        </div>
        
        <div class="about-text fade-in">
          <h2 class="section-title serif">About Luna Celestine</h2>
          <p class="section-subtitle">
            Guiding souls through cosmic wisdom for over 5 years
          </p>
          
          <div class="about-description">
            <p>
              Welcome, beautiful soul. I'm Luna Celestine, a certified astrologer and spiritual guide 
              dedicated to helping you unlock the profound wisdom written in the stars. My journey 
              into astrology began during a transformative period in my own life, where I discovered 
              the incredible power of cosmic guidance.
            </p>
            
            <p>
              With over 5 years of experience and 1000+ readings completed, I specialize in 
              birth chart analysis, relationship compatibility, and life path guidance. My approach 
              combines traditional astrological wisdom with modern psychological insights to provide 
              you with practical, empowering guidance.
            </p>
            
            <p>
              Every reading is a sacred conversation between you, me, and the cosmos. I believe 
              that astrology is not about predicting a fixed future, but about understanding 
              your unique cosmic blueprint and empowering you to make conscious choices aligned 
              with your highest potential.
            </p>
          </div>
          
          <div class="about-features">
            <div class="feature">
              <Heart :size="24" class="feature-icon" />
              <div>
                <h4>Compassionate Guidance</h4>
                <p>Every reading is delivered with love, empathy, and deep understanding</p>
              </div>
            </div>
            
            <div class="feature">
              <Award :size="24" class="feature-icon" />
              <div>
                <h4>Certified Expertise</h4>
                <p>Professionally trained with certifications in Western and Vedic astrology</p>
              </div>
            </div>
            
            <div class="feature">
              <Users :size="24" class="feature-icon" />
              <div>
                <h4>Trusted by Many</h4>
                <p>Over 500 satisfied clients who've found clarity and direction</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.about-content {
  display: grid;
  grid-template-columns: 1fr 1.5fr;
  gap: 4rem;
  align-items: center;
}

.image-container {
  position: relative;
  width: 300px;
  height: 300px;
  margin: 0 auto;
}

.astrologer-photo {
  width: 100%;
  height: 100%;
  object-fit: cover;
  border-radius: 50%;
  border: 4px solid rgba(99, 102, 241, 0.3);
  position: relative;
  z-index: 2;
}

.image-glow {
  position: absolute;
  top: -10px;
  left: -10px;
  right: -10px;
  bottom: -10px;
  background: var(--gradient-starlight);
  border-radius: 50%;
  opacity: 0.3;
  filter: blur(20px);
  z-index: 1;
  animation: pulse 3s ease-in-out infinite;
}

.about-description {
  margin: 2rem 0;
}

.about-description p {
  margin-bottom: 1.5rem;
  color: var(--text-muted);
  line-height: 1.8;
}

.about-features {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.feature {
  display: flex;
  align-items: flex-start;
  gap: 1rem;
  padding: 1rem;
  background: rgba(255, 255, 255, 0.03);
  border-radius: 12px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  transition: all 0.3s ease;
}

.feature:hover {
  background: rgba(255, 255, 255, 0.05);
  transform: translateX(5px);
}

.feature-icon {
  color: var(--starlight);
  margin-top: 0.2rem;
  flex-shrink: 0;
}

.feature h4 {
  font-weight: 600;
  margin-bottom: 0.5rem;
  color: var(--text-light);
}

.feature p {
  color: var(--text-muted);
  font-size: 0.9rem;
  line-height: 1.5;
}

@media (max-width: 768px) {
  .about-content {
    grid-template-columns: 1fr;
    gap: 2rem;
    text-align: center;
  }
  
  .image-container {
    width: 250px;
    height: 250px;
  }
  
  .about-features {
    text-align: left;
  }
}
</style>
